name: doctor-chat
channels:
  - conda-forge
dependencies:
  - python=3.10
  - transformers=4.31.0
  - transformers
  - accelerate=0.21.0
  - pip
  - pip:
    - trl==0.4.7
    - peft==0.4.0
    - torch==2.5.1
    - torchvision==0.20.1
    - torchaudio==2.5.1
    - pytorch-gpu==0.0.1
    - rouge_score
    - tensorboard==2.18.0
    - bitsandbytes
